version: '3.8'
services:

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - task-network
    volumes:
      - mongo-data:/data/db

  # FIX SDE-1: Added Redis to docker-compose — was missing for local dev
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - task-network

  task-api:
    build: .
    container_name: task-api
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
      - kafka          # ADD THIS
    networks:
      - task-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/taskdb
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_CACHE_TYPE=redis
      # FIX SDE-2: Secrets as env vars — not hardcoded in source
      - JWT_SECRET=local-dev-only-secret-key-32chars!!
      - APP_USERNAME=admin
      - APP_PASSWORD=admin123
      - REDIS_HOST=redis
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092   # ADD THIS
      - CSV_FILE_PATH=tasks.csv              # ADD THIS

networks:
  task-network:

volumes:
  mongo-data:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - task-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - task-network

