spring.data.mongodb.uri=mongodb://mongodb-service:27017/taskdb
# ===============================
# ACTUATOR CONFIG (for Kubernetes health checks)
# ===============================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


management.endpoints.web.exposure.include=health


management.endpoints.health.show-details=always

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework=INFO
logging.level.org.mongodb=INFO